version: "1.0"
services:
  # frontend:
  #   build: ./frontend
  #   container_name: frontend-container
  #   # volumes:
  #   #   - ./frontend:/frontend
  #   depends_on:
  #     - backend
  #   ports:
  #     - "5173:5173"

  backend:
    build: ./server
    container_name: backend-container
    # volumes:
    #   - ./server:/server
    ports:
      - 8080:8080
